spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanted_my_post
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          sql: trace
